### ISSUE TITLE
(Fixed) Invalid CRunValue typing returns null, causing a crash upon right clicking the CRunApp

### ISSUE THREAD

**Issue by Iaon0** [CTFAK/CTFPV#1]
Everything else works as far as I know. May be a computer issue or something I am missing but I don't know.

https://github.com/CTFAK/CTFPV/assets/119998941/d0f05a73-3f93-4630-a7b2-0c15f0907bf7

**Comment by AITYunivers** [comment]
I have already rectified this issue for a future update.
