### ISSUE TITLE
(Fixed) Editing a TextBox being ignored due to the Undo Action.

### ISSUE THREAD

**Issue by Iaon0** [CTFAK/CTFPV#2]
https://github.com/CTFAK/CTFPV/assets/119998941/e1f4fc9b-a4d9-47f5-916b-253c7c054d03

**Comment by AITYunivers** [comment]
Not a crash, don't make issues for non-crashes. The program is in beta for a reason.

**Comment by AITYunivers** [comment]
Decided it's unreasonable of me to close issues just because I'm not done with a program I released for public testing.
