### ISSUE TITLE
(Invalid) Editing values not used by renderer, not being used by the renderer.

### ISSUE THREAD

**Issue by Wario3493** [CTFAK/CTFPV#3]
I am trying to edit the values of a game called FNaC 2.0, but whenever I click on any of the boxes, they do nothing. I have tried changing different animation sprites, changing the object's visibility, basically everything, but nothing works.

**Comment by AITYunivers** [comment]
Not really supposed to, it's how the engine's coded. A lot of things are only there for the code to reference, so trying to edit the visibility among other things only makes the code think it's invisible, not actually make it invisible. For that to work I'd more likely than not need to actually hook into the application which would just end up being another project entirely.
