### ISSUE TITLE
(Fixed) If the file path is longer than 255 characters, a crash will occur when loading the icon.

### ISSUE THREAD

**Issue by derric-young** [CTFAK/CTFPV#4]
attempting to load it causes it to crash

**Comment by AITYunivers** [comment]
Can you send the file path of your exe? I might know why.

**Comment by AITYunivers** [comment]
Try the [new release](https://github.com/CTFAK/CTFPV/releases/tag/CTFPVBeta4) and let me know if the issue still occurs.

**Comment by derric-young** [comment]
it work's
